auth:
  strategy: anonymous

deployment:
  pod_labels:
    sidecar.istio.io/inject: "false"
  logger:
    log_level: debug

external_services:
  tracing:
    enabled: true
    use_grpc: false
    in_cluster_url: 'http://tracing.istio-system.svc/jaeger'
  grafana:
    enabled: true
    url: 'http://grafana.${EXTERNAL_DOMAIN}'
    in_cluster_url: http://grafana.istio-system.svc:3000
  prometheus:
    url: "${KIALI_PROMETHEUS_URL}"
