# https://github.com/kiali/helm-charts/blob/master/kiali-server/values.yaml
auth:
  strategy: anonymous

deployment:
  pod_labels:
    sidecar.istio.io/inject: "false"
  logger:
    log_level: debug

external_services:
  tracing:
    enabled: true
    provider: "tempo"
    in_cluster_url: http://tempo.telemetry:3100
    url: http://tempo.${EXTERNAL_DOMAIN}:3100 
    use_grpc: true
    grpc_port: 9095
  grafana:
    enabled: true
    url: 'http://grafana.${EXTERNAL_DOMAIN}'
    in_cluster_url: http://grafana.telemetry.svc:80
  prometheus:
    url: 	http://mimir-nginx.telemetry.svc:80/prometheus
