kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

featureGates:
  EphemeralContainers: true

networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  # podSubnet: "10.244.0.0/16"
  # disableDefaultCNI: true

nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
