dashboard:
  enabled: true
  domain: "${OAM_DOMAIN}"
#loadBalancerIP: "${TRAEFIK_LOADBALANCERIP}"
#externalIP: "${TRAEFIK_EXTERNALIP}"
serviceType: NodePort
service:
  nodePorts:
    http: 30080
    https: 30443
rbac:
  enabled: true
ssl:
  enabled: true
metrics:
  prometheus:
    enabled: true
kubernetes:
  ingressEndpoint:
    useDefaultPublishedService: true
image: "rancher/library-traefik"
tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
